### ISSUE TITLE
icons in latest appimage don't work in ubuntu 20.04

### ISSUE THREAD

**Issue by soredake** [PaulCombal/SamRewritten-legacy#79]
![Screenshot_20200702_180059](https://user-images.githubusercontent.com/5204968/86375135-fed4f000-bc8d-11ea-80dc-2113c2551ea0.png)

**Comment by wgpierce** [comment]
Fixed in https://github.com/PaulCombal/SamRewritten/issues/72. Please try latest master. I'll make a new appimage sometime since we've accrued a few fixes by now.

*Edit: Now the fix is in master.

**Comment by PaulCombal** [comment]
@wgpierce not sure of that, iirc the title bar icons worked correctly in #72

**Comment by wgpierce** [comment]
@soredake are you still seeing this issue in the latest AppImage?

**Comment by soredake** [comment]
Still not working with latest "for ubuntu 18.04" versions, last version with working icons is this https://github.com/PaulCombal/SamRewritten/releases/download/201912/SamRewritten-ab06374-x86_64.AppImage

**Comment by kbakdev** [comment]
Yea, these icons are still problematic

![image](https://user-images.githubusercontent.com/56700396/95791019-c4dda600-0ce0-11eb-8b48-6eb78175faf3.png)

There is listing:
```
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so

(samrewritten:15858): Gtk-WARNING **: 23:14:56.825: Theme parsing error: gtk.css:1511:23: 'font-feature-settings' is not a valid property name

(samrewritten:15858): Gtk-WARNING **: 23:14:56.828: Theme parsing error: gtk.css:3437:25: 'font-feature-settings' is not a valid property name

(samrewritten:15858): Gtk-WARNING **: 23:14:56.829: Theme parsing error: gtk.css:3899:23: 'font-feature-settings' is not a valid property name

(samrewritten:15858): Gtk-WARNING **: 23:14:56.895: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

**Comment by tskxz** [comment]
I got the lastest appimage. For me, doesnt show the images too  
![Screenshot from 2021-02-17 11-57-08](https://user-images.githubusercontent.com/47666341/108201164-5b9af300-7117-11eb-8366-35c2ba5e5d1f.png)

```
/tmp/.mount_SamRewRJlM65/usr/bin/../lib/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so

(samrewritten:26615): Gtk-WARNING **: 11:58:16.502: Theme parsing error: gtk.css:1521:23: 'font-feature-settings' is not a valid property name

(samrewritten:26615): Gtk-WARNING **: 11:58:16.507: Theme parsing error: gtk.css:3460:25: 'font-feature-settings' is not a valid property name

(samrewritten:26615): Gtk-WARNING **: 11:58:16.509: Theme parsing error: gtk.css:3922:23: 'font-feature-settings' is not a valid property name

(samrewritten:26615): Gtk-WARNING **: 11:58:16.696: Could not load a pixbuf from icon theme.

```
